# Generated by Django 5.2.3 on 2025-06-29 15:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.post_image_path),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.user_profile_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
