# Generated by Django 5.2.3 on 2025-07-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_post_picture_alter_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='occupation',
        ),
    ]
