# Generated by Django 5.2.3 on 2025-07-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth0_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
